### ISSUE TITLE
Rebase starting from where we forked.

### ISSUE THREAD

**Issue by benthayer** [crypto-bonds/blockchain-server#18]
I want to rebase this so that it can be our repository and not a fork. Basically, the initial commit will be all the code from https://github.com/delventhalz/pirate-talk then everything after that will be the same.

This makes sense logically since we never intend to merge back with pirate-talk:master. The repo will no longer show up as a fork, making it seem more official. We can give credit to https://github.com/delventhalz/pirate-talk in the readme. Once we do this, our contributions show up at the top of the contributors list. Also, any contributions we make will be shown in our contribution history.

Can I get written confirmation from @pkgamma @Jonathannsegal @alifirst01 @seantm2 that you guys also want to do this?

**Comment by Jonathannsegal** [comment]
yes this is fine, I'm okay with it

**Comment by alifirst01** [comment]
I found this article on difference between forking and cloning. Basically you fork when the original project gets replicated in its entirety to begin life as a new and separate entity that may move on in its own direction.
https://thenewstack.io/getting-legit-with-git-and-github-cloning-and-forking/

I am not sure what the standard procedure for this in open source community. What do you think?

**Comment by benthayer** [comment]
The most common use of a fork is to merge back into the main repo. The pirate talk code was meant to be an example, so, I think it makes sense to put it in our own repo. It'll look cleaner and we can have commits show up on our contribution history

**Comment by pkgamma** [comment]
I think that sounds fine, but I am not sure if it is the most ethical thing we can do. If we do clone it, we will have to cite the source repository somewhere in our documentation, that's for sure. It's up to you guys to decide.

**Comment by seantm2** [comment]
If you think this is for the best, then this sounds good to me

**Comment by benthayer** [comment]
https://github.com/crypto-bonds/transaction-processor
